### ISSUE TITLE
Eating food doesn't seem to actually fill you when using click-drag

### ISSUE THREAD

**Issue by Greenjoe12345** [PyrelightSS13/Pyrelight#23]
#### Description of issue
I was playing as a drake, hunting rabbits, as you do, but, when I tore them apart and ate the tasty innards, it did not sate my hunger, even after 3 rabbits and a mouse :(

#### Difference between expected and actual behavior
eating food should fill you

#### Steps to reproduce
eat

#### Specific information for locating
It was as a drake, using the click-dragging food to the mob to eat, IDK if other species are affected

#### Client version, Server revision & Game ID
 a78144ac415c7377c29972004038165ea15b66f4 - dev - 2024-07-13

cuG-avol

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Spookerton** [comment]
From cursory examination, I think this is down to /decl/material/solid/organic/meat not setting a value for nutriment_factor

**Comment by MistakeNot4892** [comment]
Fixed on Neb.
