### ISSUE TITLE
switching between characters in character setup causes tail oddness

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#28]
#### Description of issue
![image](https://github.com/user-attachments/assets/fe36fa4b-e3a6-45ba-a7c1-22154b6e367d)
hnoll tail on kobl character
![image](https://github.com/user-attachments/assets/f33ccdfb-8cce-45a6-8b0f-1a440308c2c3)
hnoll tail on meredrake character

#### Difference between expected and actual behavior
hnoll tail too persistent

#### Steps to reproduce
swap between characters.  Dunno.

#### Specific information for locating

generally below the waist

#### Length of time in which bug has been known to occur

discovered tonight

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 9e7af537a6bb58b7c0238aaf4cc7e0031f303d25 - volatile - 2024-07-20
Game ID: cuN-dFth
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed on main Neb.
