### ISSUE TITLE
meredrake tails MIA

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#29]
#### Description of issue
![image](https://github.com/user-attachments/assets/0f380d76-5031-4afc-af3b-2c1ba0915791)
tail does not appear in character select

![image](https://github.com/user-attachments/assets/639570ae-2243-443b-83b3-2b84ef9c30e8)
nor in game

#### Difference between expected and actual behavior
meredrakes look odd without tails

#### Steps to reproduce
create drake character, hop into game

#### Specific information for locating

below the waist

#### Length of time in which bug has been known to occur

discovered today

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 9e7af537a6bb58b7c0238aaf4cc7e0031f303d25 - volatile - 2024-07-20
Game ID: cuN-dFth
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed on main Neb.
