### ISSUE TITLE
stew has no flavor

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#30]
#### Description of issue
stew with 2 kinds of mushroom, carrots, cabbaga, and venison broth came back with flavor of salt and water

#### Difference between expected and actual behavior
ideally, it would have flavor

#### Steps to reproduce
make stew of your preference

#### Specific information for locating

in a bowl, a stock pot, or a cup

#### Length of time in which bug has been known to occur

today

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 9e7af537a6bb58b7c0238aaf4cc7e0031f303d25 - volatile - 2024-07-20
Game ID: cuN-dFth
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Hopefully fixed on volatile.
