### ISSUE TITLE
meathooks are overly restrictive of user/victim position

### ISSUE THREAD

**Issue by out-of-phaze** [PyrelightSS13/Pyrelight#68]
should be a bit more permissive according to Loaf

**Comment by out-of-phaze** [comment]
(needs more info on what exactly needs to change, imo, @MistakeNot4892?)

**Comment by MistakeNot4892** [comment]
At the moment it will silently fail if the corpse isn't also adjacent to the hook. It should either have feedback or move the corpse closer imo. The hook could also use a 1-alpha outline for clickability.

**Comment by MistakeNot4892** [comment]
Fixed in https://github.com/NebulaSS13/Nebula/pull/4462
