### ISSUE TITLE
masterlist of dungeon crawling issues from 9/1/24 - some may not be issues but player deficiencies

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#87]
#### Description of issue
This is more a personal tracker than anything else - if anyone wants to respond to this, it's more than welcome, but I do not hope for official response regarding most of these items.

-The sunken keep locks should have an associated key hidden somewhere.  This may already be done, but after what felt like a thorough search I found no keys for the keep.
-Zombies may be too easy now.  I upped my character's melee combat skills to master, though, so more testing at other levels is required.
-It's VERY easy to end up doused in lamp oil by stepping into water.  This is also very funny.

#### Difference between expected and actual behavior
n/a

#### Steps to reproduce
n/a

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
I have put stuff in place to address these issues (other than lamp oil) on current dev, feel free to reopen if I missed any or if they need further adjustment.
