### ISSUE TITLE
Sledgehammer ideas

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#88]
#### Description of issue
-Sledgehammer does not seem to do more damage than any other melee weapon.  It also slices doors. 
![image](https://github.com/user-attachments/assets/3ffa21ac-1569-457e-9ab5-ecfa3beaf4f9)
It would be cool if blunt weapons had an added knockdown chance.  This is not a priority.

#### Difference between expected and actual behavior
Who even sharpens a sledgehammer to a slicing edge?  It's unheard of.

String ideas for sledgehammer attacks:
'brutalizes'
'bludgeons'
'slaps'
'beats on'
'crushes'
'strikes'
'bashes'
'hammers'

#### Steps to reproduce
Grab sledgehammer, muck about with it for a while.

#### Specific information for locating

possibly smaller hammers too, I did not check.
![image](https://github.com/user-attachments/assets/93ef2f07-35a1-4f2c-8147-b3eb3a534f82)
Update: I have now checked and this remains consistent with smaller hammers.

#### Length of time in which bug has been known to occur

Noticed today.  

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: c5d8aeb2a1dd9e512ade46b83aa2feb987d06a02 - volatile - 2024-09-01
Game ID: cvu-aNjb
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Going to call the knockback/knockdown request out of scope for now, the other issues are addressed in the linked PR. Remind me about knockdown if/when I start working on melee/polearms again.
