### ISSUE TITLE
OOC-Text-Color verb not working

### ISSUE THREAD

**Issue by ZirconiumWit** [PyrelightSS13/Pyrelight#94]
#### Description of issue
I have the red admin OOC color and I tried to change the color with OOC-Text-Color verb, but it DID NOT CHANGE.

This is of the utmost importance.

#### Difference between expected and actual behavior
I wanted green ooc text color and when I input that color it did not work.

#### Steps to reproduce
Enter OOC-Text-Color verb and select 'Pick new color' and put your color in, and you'll be so, so sad when you keep the original color.

#### Specific information for locating

OOC-Text-Color, this is a verb

#### Length of time in which bug has been known to occur

I discovered it today.  (9/26/24)

#### Client version, Server revision & Game ID

Client Version: 515
Server Revision: 02afce0dd5f3b82750e87c9615239a4de4fffdff - volatile - 2024-09-26
Game ID: cvT-dEpP
Current map: Shaded Hills

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] Issue is related to Pyrelight-specific changes
- [x] [Couldn't find an existing issue about this](https://github.com/PyrelightSS13/Pyrelight/issues)

**Comment by out-of-phaze** [comment]
![image](https://github.com/user-attachments/assets/d479e096-a989-4606-a9fa-f695247116fc) ^ taken from the pyrelight box
you can set your pref when the config option is off but it won't actually apply. not a bug but i agree it could be clearer
